version: 2.1
executors:
  default:
    working_directory: ~/nextjs-nestjs-graphql
    docker:
      - image: node:14

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key: npm-v2-{{ checksum "frontend/yarn.lock" }}

  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: npm-v2-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ~/nextjs-nestjs-graphql/frontend/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          working_directory: ~/nextjs-nestjs-graphql/frontend
          name: Install dependencies
          command: yarn
      - save_npm

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          working_directory: ~/nextjs-nestjs-graphql/frontend
          name: Lint
          command: yarn lint
      - save_npm

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          working_directory: ~/nextjs-nestjs-graphql/frontend
          name: Build
          command: yarn build
      - save_npm

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          working_directory: ~/nextjs-nestjs-graphql/frontend
          name: Test
          command: yarn test
      - save_npm

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - test:
          requires:
            - build

