version: '3'

services:

  mysql:
    image: nextjs-nestjs-graphql/mysql
    container_name: nextjs-nestjs-graphql-mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
     - 3306:3306
    restart: always
    volumes:
      - nextjs-nestjs-graphql-mysql-store:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/conf:/etc/mysql/conf.d

volumes:
  nextjs-nestjs-graphql-mysql-store:
